workflows:
  ios-release:
    name: NeuraPal iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Lyazid Mabrouki
    environment:
      groups:
        - code_signing
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.mentiumlabs.neurapal"
      node: 22
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Update Capacitor iOS
        script: |
          npx cap sync ios
      - name: Resolve Swift packages
        script: |
          cd ios/App
          xcodebuild -resolvePackageDependencies -project App.xcodeproj -scheme App
      - name: Fetch signing files
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Set build version
        script: |
          agvtool new-version -all 1
          agvtool new-marketing-version 1.0.0
        working_directory: ios/App
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
